### ISSUE TITLE
Format message content

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/release-toolkit#119]
It is not easy to format the message content:

Both the following fails
```
 - Defaults of the charts have been changed:
Now, the chart has two jobs configured and curated experience turned on by default:
   - `default` scrapes all targets having `prometheus.io/scrape: true`.
   Since, by default, curated_experience.enabled=true then only targets selected by the curated experience are actually scraped.
   - `newrelic` crapes all targets having `newrelic.io/scrape: true`.
   This is useful to extend the 'default-job' allowlisting all services adding the required annotation.
```
Result -> `WARN[0001] ListItem has more than 1 children            
WARN[0001] No list items found under header "Enhancements" `

```
 - Defaults of the charts have been changed:
Now, the chart has two jobs configured and curated experience turned on by default:
  
  `default` scrapes all targets having `prometheus.io/scrape: true`.
   Since, by default, curated_experience.enabled=true then only targets selected by the curated experience are actually scraped.
   
   `newrelic` crapes all targets having `newrelic.io/scrape: true`.
   This is useful to extend the 'default-job' allowlisting all services adding the required annotation.

```

The result is without the description-> `Defaults of the charts have been changed:
Now, the chart has two jobs configured and curated experience turned on by default:`

**Comment by roobre** [comment]
Change entries are intended to be oneliners. The main reason for this is that, if we allowed multiline change entries, it would be really hard to tell when two lines are two entries or a two-line one.

I think the current way of doing this is putting a shorter change oneliner, and put the large explanation out of the change type headers so it is captured as notes.

**Comment by paologallinaharbur** [comment]
I saw that there are the "Notes". I guess it is fine :)
