### ISSUE TITLE
Inconsistent CHANGELOG link generation for dependency versions

### ISSUE THREAD

**Issue by marcsanmi** [newrelic/release-toolkit#174]
The release toolkit isn't generating correct CHANGELOG links for dependencies in some cases. Examples of this can be seen in:

- https://github.com/newrelic/nri-ecs/releases/tag/v1.10.8
- https://github.com/newrelic/infrastructure-bundle/releases/tag/v3.2.22

The issue arises because the link is generated by appending the version number without the preceding `v`. This approach isn't consistent for the integrations, but it does work for the infrastructure agent where releases are created without the leading `v`. For instance:

- https://github.com/newrelic/infrastructure-bundle/releases/tag/v3.2.21

We need to think of a solution that works in both formats.

Related: https://github.com/newrelic/nri-ecs/issues/139

**Comment by sigilioso** [comment]
It might be related to #134

**Comment by paologallinaharbur** [comment]
The issue seems bigger than expected, different repos are affected: https://github.com/newrelic/infrastructure-bundle/releases/tag/v3.2.23

**Comment by paologallinaharbur** [comment]
Fixed, the root cause was the dictionary
